import json
import logging
import os
import re
import shutil
import subprocess
import tempfile
import time
from datetime import datetime, timezone
from uuid import uuid4

import yaml

log = logging.getLogger(__name__)

# Numeric prefix pattern: "01 Section Name" → display as "Section Name"
_NAV_PREFIX_RE = re.compile(r'^\d+\s+')

DOCS_CONTENT_DIR = os.environ.get("DOCS_CONTENT_DIR", "/docs-content")
MKDOCS_CONFIG_DIR = os.environ.get("MKDOCS_CONFIG_DIR", "/mkdocs-config")
MKDOCS_YML = os.path.join(MKDOCS_CONFIG_DIR, "mkdocs.yml")
# The generated nav lives in a SEPARATE, git-ignored child config that INHERITs
# mkdocs.yml. mkdocs.yml (git-tracked) holds only hand-maintained config +
# API-managed redirect_maps; the volatile, regenerated-every-deploy nav is written
# here so it can never dirty the tracked file. The deploy builds THIS file.
MKDOCS_NAV_YML = os.path.join(MKDOCS_CONFIG_DIR, "mkdocs.nav.yml")
MANIFEST_PATH = os.path.join(DOCS_CONTENT_DIR, ".docs_manifest.json")
GENERATOR_STAMP = "<!-- Generated by ccm-docs -->"

# Live directory nginx serves (mkdocs default site_dir = <config dir>/site).
SITE_DIR = os.path.join(MKDOCS_CONFIG_DIR, "site")
# Staging build target — OFF the served volume, so the clean mkdocs build never
# touches the directory nginx serves. The staged build is then rsync'd into SITE_DIR
# atomically per file (see _build_site), eliminating the mass-404 rebuild window.
STAGING_SITE_DIR = os.environ.get("DOCS_STAGING_SITE_DIR", "/tmp/docs-site-build")


def run(
    pages: list[dict],
    dry_run: bool = False,
    section_order: dict[str, int] | None = None,
) -> dict:
    deploy_id = str(uuid4())
    log.info("[%s] deploy start — %d pages, dry_run=%s", deploy_id, len(pages), dry_run)

    # Basic validation
    for page in pages:
        if not page["content"].strip():
            raise RuntimeError(f"Empty content for {page['path']}")
        if not page["path"].endswith(".md"):
            raise RuntimeError(f"Invalid path: {page['path']}")

    # Build nav up-front — surface conflicts before we write files.
    nav_block = build_nav(pages, section_order=section_order)

    current_paths = {p["path"] for p in pages}
    prev_paths = _load_manifest()
    to_delete = prev_paths - current_paths  # only paths we previously owned

    # Stage all files to a temp dir, then sync into DOCS_CONTENT_DIR.
    # Write staging first so if crash happens mid-stage, content dir is untouched.
    # DOCS_CONTENT_DIR may be a Docker volume mount (can't rename), so we sync
    # contents rather than swapping the directory itself.
    stage_dir = tempfile.mkdtemp(prefix="docs-build-")
    try:
        for page in pages:
            dest = os.path.join(stage_dir, page["path"])
            os.makedirs(os.path.dirname(dest), exist_ok=True)
            with open(dest, "w") as f:
                f.write(_augment_content(page))

        if not dry_run:
            # Log violations before overwriting
            for page in pages:
                dst = os.path.join(DOCS_CONTENT_DIR, page["path"])
                if os.path.exists(dst):
                    with open(dst) as f:
                        on_disk = f.read()
                    if on_disk != _augment_content(page):
                        log.warning(
                            "[VIOLATION] %s was edited outside the control plane — "
                            "overwriting with DB state. Use Docs API to make changes.",
                            page["path"],
                        )

            # Purge all .md files and empty dirs from content dir, then copy staged
            for dirpath, _, filenames in os.walk(DOCS_CONTENT_DIR, topdown=False):
                for fname in filenames:
                    if fname.endswith(".md"):
                        os.remove(os.path.join(dirpath, fname))
                # Remove empty subdirs (but not DOCS_CONTENT_DIR itself)
                if dirpath != DOCS_CONTENT_DIR and not os.listdir(dirpath):
                    os.rmdir(dirpath)

            # Copy all staged files into content dir
            for page in pages:
                src = os.path.join(stage_dir, page["path"])
                dst = os.path.join(DOCS_CONTENT_DIR, page["path"])
                os.makedirs(os.path.dirname(dst), exist_ok=True)
                shutil.copy2(src, dst)

            # Write manifest
            _save_manifest(current_paths)

            log.info("[%s] deploy complete: %d files written, %d removed",
                     deploy_id, len(current_paths), len(to_delete))
    finally:
        shutil.rmtree(stage_dir, ignore_errors=True)

    if not dry_run:
        _write_nav_config(nav_block)
        build_ms = _build_site(deploy_id)
    else:
        log.info("[%s] dry_run nav:\n%s", deploy_id, yaml.dump(nav_block, sort_keys=False))
        build_ms = None

    result = {
        "deploy_id": deploy_id,
        "pages_written": len(pages),
        "files_removed": len(to_delete),
        "dry_run": dry_run,
        "build_time_ms": build_ms,
    }
    if dry_run:
        result["nav"] = nav_block
    log.info("[%s] deploy complete: %s", deploy_id, {k: v for k, v in result.items() if k != "nav"})
    return result


def _build_site(deploy_id: str) -> int:
    """Build the full site to a staging dir, then sync it into the live served dir
    WITHOUT ever emptying the latter — returns elapsed milliseconds.

    Why not just `mkdocs build --clean` into the served dir: `--clean` wipes the
    output dir at the start of the build and repopulates it over the whole build
    (seconds to minutes as the corpus grows). nginx serves that same dir, so every
    URL 404s for the entire build. Instead we build into STAGING_SITE_DIR (off the
    served volume) and rsync it into SITE_DIR: rsync writes each file to a temp and
    renames it (atomic per file) and `--delete` prunes removed pages, so nginx always
    serves a complete site and only genuinely-changed files are touched. `--checksum`
    keeps the churn to real content changes (mkdocs rewrites every file's mtime each
    build, which a time-based sync would treat as all-changed)."""
    t0 = time.monotonic()
    build = subprocess.run(
        # Build the generated child config (INHERITs mkdocs.yml, supplies nav).
        ["mkdocs", "build", "--config-file", MKDOCS_NAV_YML, "--clean",
         "--site-dir", STAGING_SITE_DIR],
        capture_output=True,
        text=True,
    )
    if build.returncode != 0:
        log.error("[%s] mkdocs build failed:\n%s", deploy_id, build.stderr[-2000:])
        raise RuntimeError(f"mkdocs build failed: {build.stderr[-500:]}")
    os.makedirs(SITE_DIR, exist_ok=True)
    sync = subprocess.run(
        ["rsync", "-a", "--checksum", "--delete",
         STAGING_SITE_DIR + "/", SITE_DIR + "/"],
        capture_output=True,
        text=True,
    )
    if sync.returncode != 0:
        log.error("[%s] site sync failed:\n%s", deploy_id, sync.stderr[-2000:])
        raise RuntimeError(f"site sync failed: {sync.stderr[-500:]}")
    elapsed_ms = int((time.monotonic() - t0) * 1000)
    log.info("[%s] mkdocs build + atomic sync OK in %dms", deploy_id, elapsed_ms)
    return elapsed_ms


def _load_manifest() -> set:
    try:
        with open(MANIFEST_PATH) as f:
            data = json.load(f)
        return set(data.get("managed_files", []))
    except FileNotFoundError:
        return set()


def _augment_content(page: dict) -> str:
    """Prepend generator stamp and insert a Last Updated line after H1."""
    content = page["content"]
    updated_at = page.get("updated_at")

    # Strip any pre-existing generator stamp (idempotent)
    lines = content.split("\n")
    lines = [l for l in lines if l.strip() != GENERATOR_STAMP]
    content = "\n".join(lines)

    if not updated_at:
        return f"{GENERATOR_STAMP}\n{content}"

    if isinstance(updated_at, datetime):
        ts = updated_at.strftime("%Y-%m-%d %H:%M")
    else:
        ts = str(updated_at)[:16].replace("T", " ")

    ver = page.get("version")
    suffix = f" · v{ver}" if ver else ""
    time_stamp = f"*Last updated: {ts}{suffix}*"

    # Strip any pre-existing manual "Last updated" lines (stale, from pre-API era)
    lines = content.split("\n")
    lines = [l for l in lines if not re.match(r"^\*[Ll]ast updated:.*\*$", l.strip())]
    content = "\n".join(lines)

    # Insert after H1
    lines = content.split("\n")
    for i, line in enumerate(lines):
        if line.startswith("# "):
            before = "\n".join(lines[: i + 1])
            after = "\n".join(lines[i + 1 :]).lstrip("\n")
            return f"{GENERATOR_STAMP}\n{before}\n\n{time_stamp}\n\n{after}\n"

    # No H1 found — prepend
    return f"{GENERATOR_STAMP}\n{time_stamp}\n\n{content.rstrip()}\n"


def _save_manifest(paths: set) -> None:
    tmp = MANIFEST_PATH + ".tmp"
    with open(tmp, "w") as f:
        json.dump({
            "managed_files": sorted(paths),
            "deployed_at": datetime.now(timezone.utc).isoformat(),
        }, f, indent=2)
    os.replace(tmp, MANIFEST_PATH)


class NavConflict(RuntimeError):
    """Raised when nav_path assignments produce an unresolvable tree conflict.
    Subclasses RuntimeError so existing `except RuntimeError` handlers still catch it."""

    def __init__(self, kind: str, segment: str, message: str):
        self.kind = kind        # "leaf-vs-section" | "case-collision" | "invalid"
        self.segment = segment
        self.message = message
        super().__init__(message)


def build_nav(
    pages: list[dict],
    *,
    strict: bool = True,
    section_order: dict[str, int] | None = None,
):
    """Fold pages into an mkdocs-shaped nav tree.

    strict=True   → raises NavConflict on first conflict (used by deploy).
    strict=False  → returns (tree, conflicts) so callers can inspect a best-effort
                    tree alongside any offending pages (used by read endpoints).
    section_order → dict[section_name → sort_order] controlling top-level order.
                    None falls back to DEFAULT_SECTION_ORDER.
    """
    tree: dict = {}
    conflicts: list[dict] = []
    home_path: str | None = None

    for page in pages:
        nav_path = page["nav_path"]
        if nav_path == "Home":
            if home_path is not None and home_path != page["path"]:
                msg = (f"Two pages both claim nav_path 'Home': {home_path!r} and "
                       f"{page['path']!r}. Exactly one page may be Home.")
                if strict:
                    raise NavConflict("duplicate-home", "Home", msg)
                conflicts.append({
                    "kind": "duplicate-home", "nav_path": "Home", "segment": "Home",
                    "detail": msg, "paths": [page["path"]],
                })
                continue
            home_path = page["path"]
            continue
        parts = nav_path.split("/")
        if len(parts) < 2:
            conflict = {
                "kind": "invalid",
                "nav_path": nav_path,
                "segment": parts[0] if parts else "",
                "detail": "nav_path must contain at least one '/'",
                "paths": [page["path"]],
            }
            if strict:
                raise NavConflict(conflict["kind"], conflict["segment"], conflict["detail"])
            conflicts.append(conflict)
            continue
        try:
            _nav_insert(tree, parts, page["path"])
        except NavConflict as e:
            if strict:
                raise
            conflicts.append({
                "kind": e.kind,
                "nav_path": nav_path,
                "segment": e.segment,
                "detail": e.message,
                "paths": [page["path"]],
            })

    nav: list = []
    if home_path:
        nav.append({"Home": home_path})
    nav.extend(_nav_serialize(tree, top_level=True, section_order=section_order))

    if strict:
        return nav
    return nav, conflicts


def distinct_section_paths(pages: list[dict]) -> list[str]:
    """Flat, sorted list of every intermediate section path across active pages.
    Example: page with nav_path 'Services/Spacen/Operations' contributes
    ['Services', 'Services/Spacen']."""
    sections: set[str] = set()
    for page in pages:
        nav_path = page["nav_path"]
        if nav_path == "Home":
            continue
        parts = nav_path.split("/")
        for i in range(1, len(parts)):
            sections.add("/".join(parts[:i]))
    return sorted(sections)


def _normalize_segment(key: str) -> str:
    """Canonical form for detecting sibling collisions (strip numeric prefix,
    trim whitespace, casefold). Two keys with the same canonical form render
    identically in the sidebar even if stored as distinct dict keys."""
    display = _NAV_PREFIX_RE.sub("", key)
    return display.strip().casefold()


def _sibling_collision(node: dict, key: str) -> str | None:
    """Return an existing sibling key whose canonical form matches `key`'s,
    but with a different raw string — None if no collision."""
    target = _normalize_segment(key)
    for existing in node:
        if existing == key:
            return None  # exact match — reusing this sibling, not colliding
        if _normalize_segment(existing) == target:
            return existing
    return None


def _nav_insert(node: dict, parts: list, path: str) -> None:
    key = parts[0]

    collision = _sibling_collision(node, key)
    if collision is not None:
        raise NavConflict(
            "case-collision", key,
            f"nav_path segment {key!r} collides with existing sibling {collision!r} "
            f"(same canonical form). Reuse {collision!r} verbatim or rename one of them."
        )

    if len(parts) == 2:
        leaf_key = parts[1]
        existing = node.get(key)
        if isinstance(existing, str):
            raise NavConflict(
                "leaf-vs-section", key,
                f"'{key}' is used as both a page title and a section name. "
                f"Rename the parent page's nav_path to include a sub-title "
                f"(e.g. add '/Overview'), or choose a distinct section name."
            )
        section = node.setdefault(key, {})
        leaf_collision = _sibling_collision(section, leaf_key)
        if leaf_collision is not None:
            raise NavConflict(
                "case-collision", leaf_key,
                f"nav_path leaf {leaf_key!r} collides with existing sibling "
                f"{leaf_collision!r} under {key!r} (same canonical form)."
            )
        existing_leaf = section.get(leaf_key)
        if isinstance(existing_leaf, dict):
            raise NavConflict(
                "leaf-vs-section", leaf_key,
                f"'{leaf_key}' is used as both a section name and a page title "
                f"under '{key}'. Choose a distinct leaf name."
            )
        if isinstance(existing_leaf, str) and existing_leaf != path:
            raise NavConflict(
                "duplicate-leaf", leaf_key,
                f"nav_path '{key}/{leaf_key}' is already claimed by '{existing_leaf}' "
                f"— '{path}' would clobber it silently. Give one of them a distinct "
                f"leaf name."
            )
        section[leaf_key] = path
    else:
        if key not in node:
            node[key] = {}
        elif isinstance(node[key], str):
            raise NavConflict(
                "leaf-vs-section", key,
                f"'{key}' is used as both a page title and a section name. "
                f"Rename the parent page's nav_path to include a sub-title "
                f"(e.g. add '/Overview'), or choose a distinct section name."
            )
        _nav_insert(node[key], parts[1:], path)


# Bootstrap defaults — used to seed docs.sections on first startup and as a
# fallback if the DB lookup returns nothing. The DB table is the runtime SoT.
DEFAULT_SECTION_ORDER: dict[str, int] = {
    "Getting Started": 0,
    "Sites": 1,
    "Network": 2,
    "Products & Services": 3,
    "Control Plane": 4,
    "Operations": 5,
    "Standards & Governance": 6,
    "Disaster Recovery": 7,
    "Reference": 8,
    "Guides": 9,
    "Agents & Operators": 10,
    "Archive": 99,
}


def _nav_serialize(
    node: dict,
    top_level: bool = False,
    section_order: dict[str, int] | None = None,
) -> list:
    result = []
    order_map = section_order if section_order is not None else DEFAULT_SECTION_ORDER
    # Unlisted sections sort after every listed one; stable among themselves by key
    unlisted_rank = max(order_map.values(), default=-1) + 1

    def _sort_key(key: str) -> tuple:
        display = _NAV_PREFIX_RE.sub("", key)
        if top_level:
            return (order_map.get(display, unlisted_rank), key)
        # "Index" and "Overview" always sort first within any section
        if display in ("Index", "Overview"):
            return (-1, key)
        return (0, key)

    for key in sorted(node, key=_sort_key):
        val = node[key]
        display = _NAV_PREFIX_RE.sub("", key)  # strip "01 " prefix for display, sort on raw key
        if isinstance(val, str):
            result.append({display: val})
        else:
            # val is a dict: leaves are str values, sub-sections are dict values
            children = _nav_serialize(val)
            result.append({display: children})
    return result


_NAV_CONFIG_HEADER = (
    "# ⚠️  GENERATED FILE — DO NOT EDIT — git-ignored.\n"
    "#\n"
    "# The site nav, derived from PostgreSQL (Docs API), is rewritten here on every\n"
    "# deploy. It lives in its own child config — which INHERITs everything else from\n"
    "# mkdocs.yml — so the volatile, regenerated-every-deploy nav never dirties the\n"
    "# git-tracked mkdocs.yml (that recurring drift is exactly what this split fixes).\n"
    "#\n"
    "# SOURCE OF TRUTH:  PostgreSQL (via Docs API).  The deploy builds THIS file.\n"
    "# → To change docs/nav: PUT a page via the Docs API, then POST /api/docs/deploy.\n"
)


def _write_nav_config(nav_block: list) -> None:
    """Write the generated nav to the git-ignored child config MKDOCS_NAV_YML.

    The child is a standalone mkdocs config that inherits mkdocs.yml (theme, plugins,
    redirect_maps, markdown_extensions) and supplies only ``nav``. mkdocs replaces
    (does not merge) list-valued keys across INHERIT, and mkdocs.yml no longer carries
    a ``nav`` key, so this nav is authoritative for the build. Written atomically."""
    body = yaml.dump(
        {"INHERIT": "mkdocs.yml", "nav": nav_block},
        sort_keys=False, allow_unicode=True, default_flow_style=False,
    )
    tmp = MKDOCS_NAV_YML + ".tmp"
    with open(tmp, "w") as f:
        f.write(_NAV_CONFIG_HEADER)
        f.write(body)
    os.replace(tmp, MKDOCS_NAV_YML)


# Matches redirect_maps entries: 8-space indent + valid path + ": " + valid path
_REDIRECT_ENTRY_RE = re.compile(r'^        ([a-z0-9/_-]+\.md):\s+([a-z0-9/_-]+\.md)')


def add_redirect(from_path: str, to_path: str) -> bool:
    """Append a redirect_maps entry to mkdocs.yml for a moved page.

    Returns True if a new entry was written, False if the redirect already existed.
    Idempotent: no-op if the from_path key already appears in redirect_maps.
    Inserts before '  - search' (the line after the redirect_maps block).
    redirect_maps is the one API-managed section still in mkdocs.yml (nav now lives
    in the generated mkdocs.nav.yml). Page moves are rare, so the resulting mkdocs.yml
    change is small and git-committable — unlike the nav, which churned every deploy.
    """
    with open(MKDOCS_YML) as f:
        content = f.read()

    key_prefix = f"        {from_path}:"
    if key_prefix in content:
        log.info("redirect already present for %s — skipping", from_path)
        return False

    entry = f"        {from_path}: {to_path}\n"
    marker = "  - search\n"
    if marker not in content:
        raise RuntimeError("mkdocs.yml: '  - search' anchor not found — cannot add redirect")

    new_content = content.replace(marker, entry + marker, 1)
    tmp = MKDOCS_YML + ".tmp"
    with open(tmp, "w") as f:
        f.write(new_content)
    os.replace(tmp, MKDOCS_YML)
    log.info("redirect added: %s → %s", from_path, to_path)
    return True


def parse_redirect_maps() -> dict[str, str]:
    """Parse the redirect_maps block from mkdocs.yml.

    Returns {from_path: to_path} for all entries. Reads the section between
    'redirect_maps:' and '  - search'. Skips comment lines and non-path entries.
    """
    try:
        with open(MKDOCS_YML) as f:
            content = f.read()
    except FileNotFoundError:
        return {}

    start = content.find("      redirect_maps:")
    end = content.find("  - search", start if start != -1 else 0)
    if start == -1:
        return {}

    block = content[start:end] if end != -1 else content[start:]
    redirects: dict[str, str] = {}
    for line in block.splitlines():
        m = _REDIRECT_ENTRY_RE.match(line)
        if m:
            redirects[m.group(1)] = m.group(2)
    return redirects


def _rmdir_if_empty(path: str, stop_at: str) -> None:
    while path != stop_at and os.path.isdir(path) and not os.listdir(path):
        os.rmdir(path)
        path = os.path.dirname(path)
