"""Render the authoritative PostgreSQL corpus into an atomic MkDocs release."""
from __future__ import annotations

import html
import json
import logging
import os
import re
import shutil
import subprocess
import tempfile
import time
from datetime import datetime, timezone
from pathlib import Path, PurePosixPath
from uuid import uuid4

import yaml

log = logging.getLogger(__name__)

DOCS_CONTENT_DIR = Path(os.environ.get("DOCS_CONTENT_DIR", "/docs-content"))
MKDOCS_CONFIG_DIR = Path(os.environ.get("MKDOCS_CONFIG_DIR", "/mkdocs-config"))
MKDOCS_YML = Path(os.environ.get("MKDOCS_BASE_CONFIG", str(MKDOCS_CONFIG_DIR / "mkdocs.yml")))
MKDOCS_NAV_YML = MKDOCS_CONFIG_DIR / "mkdocs.nav.yml"
SITE_DIR = Path(os.environ.get("DOCS_SITE_DIR", str(MKDOCS_CONFIG_DIR / "site")))
STAGING_SITE_DIR = Path(os.environ.get("DOCS_STAGING_SITE_DIR", "/tmp/docplane-site-build"))
MANIFEST_PATH = DOCS_CONTENT_DIR / ".docplane-manifest.json"
# Written by the compose site-init service; see _build_site and the site-init
# comment in docker-compose.yml. Must survive rsync --delete.
SITE_INIT_SENTINEL = ".docplane-site-init"
GENERATOR_STAMP = "<!-- Generated by DocPlane; edit through the API -->"
_NAV_PREFIX_RE = re.compile(r"^\d+\s+")


class NavConflict(RuntimeError):
    def __init__(self, kind: str, segment: str, message: str):
        self.kind = kind
        self.segment = segment
        self.message = message
        super().__init__(message)


class RouteConflict(RuntimeError):
    """More than one thing claims a single rendered URL.

    Every release output - a page, or a redirect stub - occupies exactly one URL.
    When two claim the same one, whichever is written last wins and the other
    silently disappears while still appearing in navigation and still certifying
    as CURRENT. Three shapes of this have reached production:

      * two active pages, e.g. ``a/b.md`` and ``a/b/index.md``;
      * a redirect whose source and target render to the same URL, so the stub
        overwrites the page it points at;
      * a redirect whose source URL belongs to a DIFFERENT active page, so the
        stub overwrites an unrelated page.

    All three are the same fact - a URL claimed twice - so they are one check.
    """

    def __init__(self, collisions: dict[str, list[str]]):
        self.collisions = collisions
        detail = "; ".join(
            f"{url} <- {', '.join(claims)}" for url, claims in sorted(collisions.items())
        )
        super().__init__(f"rendered route claimed more than once: {detail}")


class RedirectConflict(RuntimeError):
    """Redirect state that must fail publication rather than be silently omitted."""

    def __init__(self, kind: str, source: str, message: str):
        self.kind = kind
        self.source = source
        self.message = message
        super().__init__(message)


def rendered_html_path(md_path: str) -> str:
    """Site-relative HTML MkDocs emits for a Markdown path (use_directory_urls)."""
    path = PurePosixPath(md_path)
    if path.name == "index.md":
        return str(path.with_name("index.html"))
    return f"{path.with_suffix('')}/index.html"


def rendered_url(md_path: str) -> str:
    """Served URL for a Markdown path (use_directory_urls).

    ``a/b.md`` and ``a/b/index.md`` render to the SAME url, which is why a
    redirect between them cannot be represented - see validate_redirects.
    """
    path = PurePosixPath(md_path)
    if path.name == "index.md":
        parent = path.parent.as_posix()
        return "/" if parent == "." else f"/{parent}/"
    return f"/{path.with_suffix('')}/"


def validate_routes(pages: list[dict], redirects: dict[str, str] | None = None) -> None:
    """Assert every rendered URL is claimed by exactly one release output.

    Runs before the nav is built, so an unrepresentable corpus fails a dry run and
    is never promoted. Uses rendered_url() so route shape is defined in one place.
    """
    claims: dict[str, list[str]] = {}
    for page in pages:
        claims.setdefault(rendered_url(str(page["path"])), []).append(str(page["path"]))
    for source in (redirects or {}):
        claims.setdefault(rendered_url(str(source)), []).append(f"redirect:{source}")
    collisions = {url: sorted(c) for url, c in claims.items() if len(c) > 1}
    if collisions:
        raise RouteConflict(collisions)


def validate_redirects(redirects: dict[str, str], pages: list[dict]) -> dict[str, str]:
    """Check the redirect map against the active corpus; raise on anything unsound.

    OPERATIONAL INTENT. Redirect preservation is the property that makes a page
    move non-destructive, so an unrepresentable redirect must abort the release
    instead of quietly disappearing from the rendered site — which is exactly the
    failure this function exists to prevent (docplane#65: rows were recorded in
    docs.redirects, used for the state-identity hash, and never rendered, so old
    URLs 404'd while every status surface reported success).

    Chains and cycles are structurally impossible under the operation contract:
    a source may never be an active page and a target must always be one, so the
    two sets are disjoint and no target can itself be a source. That is asserted
    here rather than assumed, so a future contract change fails loudly and at
    build time instead of emitting a redirect that points at another redirect.
    """
    active = {str(page["path"]) for page in pages}
    for source, target in sorted(redirects.items()):
        if not source.endswith(".md") or not target.endswith(".md"):
            raise RedirectConflict("invalid-path", source, f"redirect {source!r} -> {target!r} must use .md paths")
        if source == target:
            raise RedirectConflict("self-redirect", source, f"{source!r} redirects to itself")
        if source in active:
            # Would shadow a live page with a redirect stub.
            raise RedirectConflict("source-is-active-page", source, f"{source!r} is an active page and cannot be a redirect source")
        if target not in active:
            raise RedirectConflict("target-missing", source, f"redirect target {target!r} is not an active page")
        if target in redirects:
            raise RedirectConflict("chain", source, f"redirect target {target!r} is itself a redirect source")
        if rendered_url(source) == rendered_url(target):
            # `a/b.md` and `a/b/index.md` are different SOURCE paths that render
            # to the same URL. A redirect between them is unrepresentable: the
            # stub would be written exactly where the target page renders,
            # replacing real content with a page that redirects to itself. A
            # move between these two shapes needs create_redirect=false, because
            # the public URL never changes and no compatibility route is needed.
            raise RedirectConflict(
                "same-rendered-url", source,
                f"{source!r} and {target!r} both render to {rendered_url(source)!r}; "
                "a redirect between them would overwrite the page with a self-redirect",
            )
    return dict(sorted(redirects.items()))


# The canonical page → domain derivation for the four-domain model. Everything
# that badges, groups or filters pages by domain must call (or mirror) this —
# the dashboard keeps a lockstep copy in static/app.js pageDomain().
# Precedence: WORK_NOTE pages are the work domain's page form wherever they
# live; the observe/ and model/ surface sections carry their domain; every
# other page is the know corpus.
_SURFACE_SECTIONS = {"observe": "observe", "model": "model"}
_DOMAIN_LABELS = {"work": "Work", "know": "Know", "model": "Model", "observe": "Observe"}

# One glyph per domain, shared across every surface (badges here; the
# dashboard and future palette/search reuse the same set): book = know,
# gears = model, graph = observe, hammer = work. Inline stroke SVGs so pages
# stay self-contained — styled by .dp-badge svg in theme.css.
_SVG_ATTRS = (
    'viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" '
    'stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"'
)
_DOMAIN_ICONS = {
    "know": (
        f'<svg {_SVG_ATTRS}><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"/>'
        '<path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"/></svg>'
    ),
    "model": (
        f'<svg {_SVG_ATTRS.replace("2.2", "2")}><circle cx="12" cy="12" r="3"/>'
        '<path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06'
        'a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09'
        'A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83'
        'l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09'
        'A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0'
        'l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09'
        'a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83'
        'l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2'
        'h-.09a1.65 1.65 0 0 0-1.51 1z"/></svg>'
    ),
    "observe": f'<svg {_SVG_ATTRS}><path d="M18 20V10M12 20V4M6 20v-6"/></svg>',
    "work": (
        f'<svg {_SVG_ATTRS.replace("2.2", "2")}>'
        '<path d="m15 12-8.373 8.373a1 1 0 1 1-3-3L12 9"/><path d="m18 15 4-4"/>'
        '<path d="m21.5 11.5-1.914-1.914A2 2 0 0 1 19 8.172V7l-2.26-2.26a6 6 0 0 0-4.202-1.756'
        'L9 2.96l.92.82A6.18 6.18 0 0 1 12 8.4V10l2 2h1.172a2 2 0 0 1 1.414.586L18.5 14.5"/></svg>'
    ),
}


def page_domain(page: dict) -> str:
    if (page.get("knowledge_class") or "").strip().upper() == "WORK_NOTE":
        return "work"
    head = str(page.get("path") or "").split("/", 1)[0]
    return _SURFACE_SECTIONS.get(head, "know")


def _badge_markup(page: dict) -> str:
    """One line of raw HTML — the page's meta strip: coloured domain badge
    (icon anatomy), quiet facet chips (knowledge class; GENERATED provenance)
    and the updated/version meta. Styled by the shared category tokens in
    mkdocs/overrides/assets/theme.css; the wrapper's data-domain drives the
    domain page tint and the reader's context bar. One line so re-augmenting
    can strip and re-insert it idempotently."""
    domain = page_domain(page)
    chips = [
        f'<span class="dp-badge dp-badge--ic" data-domain="{domain}">'
        f"{_DOMAIN_ICONS[domain]}{_DOMAIN_LABELS[domain]}</span>"
    ]
    knowledge_class = (page.get("knowledge_class") or "").strip()
    if knowledge_class and knowledge_class.upper() != "WORK_NOTE":
        label = html.escape(knowledge_class.replace("_", " ").title())
        chips.append(f'<span class="dp-chip">{label}</span>')
    if page.get("provenance") == "GENERATED":
        chips.append('<span class="dp-chip dp-chip--generated">Generated</span>')
    updated_at = page.get("updated_at")
    version = page.get("version")
    if updated_at:
        if isinstance(updated_at, datetime):
            rendered = updated_at.astimezone(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        else:
            rendered = str(updated_at).replace("T", " ")[:16] + " UTC"
        chips.append(
            '<span class="dp-meta">Updated '
            f"{rendered}{f' · v{version}' if version else ''}</span>"
        )
    return f'<p class="dp-badges" data-domain="{domain}">' + "".join(chips) + "</p>"


def _augment_content(page: dict) -> str:
    # Strip everything this function itself injects (stamp, meta strip) plus
    # the legacy italic "Last updated" marker, so re-augmenting rendered
    # output converges instead of accumulating.
    lines = [
        line for line in str(page["content"]).splitlines()
        if line.strip() != GENERATOR_STAMP
        and not line.lstrip().startswith('<p class="dp-badges"')
        and not re.match(r"^\*[Ll]ast updated:.*\*$", line.strip())
    ]
    badges = _badge_markup(page)
    head = ["", badges, ""]
    inserted = False
    output: list[str] = []
    index = 0
    while index < len(lines):
        line = lines[index]
        output.append(line)
        index += 1
        if not inserted and line.startswith("# "):
            # Canonicalise the head region: blank lines directly under the H1
            # are replaced by exactly the inserted block, keeping the function
            # a fixed point on its own output.
            while index < len(lines) and lines[index].strip() == "":
                index += 1
            output.extend(head)
            inserted = True
    if not inserted:
        while output and output[0].strip() == "":
            output.pop(0)
        output = head[1:] + output
    content = "\n".join(output).rstrip() + "\n"
    return f"{GENERATOR_STAMP}\n{content}"


def _normalize_segment(value: str) -> str:
    return _NAV_PREFIX_RE.sub("", value).strip().casefold()


def _insert(tree: dict, parts: list[str], path: str) -> None:
    node = tree
    for index, part in enumerate(parts):
        normalized = _normalize_segment(part)
        matching = next((key for key in node if _normalize_segment(key) == normalized), None)
        if matching is not None and matching != part:
            raise NavConflict(
                "case-collision",
                part,
                f"Navigation siblings {matching!r} and {part!r} normalize to the same name.",
            )
        key = matching or part
        leaf = index == len(parts) - 1
        existing = node.get(key)
        if leaf:
            if isinstance(existing, dict):
                raise NavConflict("leaf-vs-section", part, f"{part!r} is already a section.")
            if existing and existing != path:
                raise NavConflict("duplicate-leaf", part, f"{part!r} maps to multiple pages.")
            node[key] = path
        else:
            if isinstance(existing, str):
                raise NavConflict("leaf-vs-section", part, f"{part!r} is already a page.")
            node = node.setdefault(key, {})


def _serialize(tree: dict, *, top_level: bool, section_order: dict[str, int] | None) -> list:
    keys = list(tree)
    if top_level:
        order = section_order or {}
        keys.sort(key=lambda key: (order.get(key, 10_000), _normalize_segment(key)))
    else:
        keys.sort(key=_normalize_segment)
    result: list = []
    for key in keys:
        value = tree[key]
        result.append({key: _serialize(value, top_level=False, section_order=section_order) if isinstance(value, dict) else value})
    return result


def build_nav(pages: list[dict], *, strict: bool = True, section_order: dict[str, int] | None = None):
    tree: dict = {}
    conflicts: list[dict] = []
    home: str | None = None
    for page in pages:
        path = str(page["path"])
        nav_path = str(page["nav_path"])
        if nav_path == "Home":
            if home and home != path:
                conflict = NavConflict("duplicate-home", "Home", "Exactly one active page may be Home.")
                if strict:
                    raise conflict
                conflicts.append({"kind": conflict.kind, "segment": conflict.segment, "detail": conflict.message, "paths": [home, path]})
            home = path
            continue
        parts = [part.strip() for part in nav_path.split("/") if part.strip()]
        if len(parts) < 2:
            conflict = NavConflict("invalid", nav_path, "nav_path must contain a section and page label")
            if strict:
                raise conflict
            conflicts.append({"kind": conflict.kind, "segment": conflict.segment, "detail": conflict.message, "paths": [path]})
            continue
        try:
            _insert(tree, parts, path)
        except NavConflict as exc:
            if strict:
                raise
            conflicts.append({"kind": exc.kind, "segment": exc.segment, "detail": exc.message, "paths": [path]})
    nav = ([{"Home": home}] if home else []) + _serialize(tree, top_level=True, section_order=section_order)
    return nav if strict else (nav, conflicts)


def distinct_section_paths(pages: list[dict]) -> list[str]:
    sections: set[str] = set()
    for page in pages:
        nav_path = str(page["nav_path"])
        if nav_path == "Home":
            continue
        parts = nav_path.split("/")
        for index in range(1, len(parts)):
            sections.add("/".join(parts[:index]))
    return sorted(sections)


def _write_nav(nav: list, redirects: dict[str, str] | None = None) -> None:
    # docs_dir MUST be absolute and generator-owned. MkDocs defaults it to
    # "docs" relative to the config file it was invoked with, which would
    # resolve to MKDOCS_CONFIG_DIR/docs — never where DocPlane actually renders
    # the corpus (DOCS_CONTENT_DIR). Emitting it explicitly keeps the rendered
    # content the single input to the build. See _sync_base_config_assets for
    # the sibling relative-path problem this pairs with.
    payload = {"INHERIT": str(MKDOCS_YML), "docs_dir": str(DOCS_CONTENT_DIR), "nav": nav}
    # Compatibility routes are DB-derived, so they belong in the generated child
    # config beside the DB-derived nav — never appended to the hand-maintained
    # parent, which was the legacy mechanism and is why nothing rendered them
    # once the legacy writer was removed.
    #
    # MkDocs deep-merges dict-form config across INHERIT, so declaring only
    # plugins.redirects.redirect_maps here ADDS to the parent's plugin
    # configuration rather than replacing its plugin list. That is why the
    # parent declares `plugins` as a mapping; see the note in mkdocs/mkdocs.yml.
    # Restating the parent's plugins here would silently drop any plugin it
    # gains later, so do not do that.
    if redirects:
        payload["plugins"] = {"redirects": {"redirect_maps": dict(sorted(redirects.items()))}}
    MKDOCS_NAV_YML.parent.mkdir(parents=True, exist_ok=True)
    temp = MKDOCS_NAV_YML.with_suffix(".tmp")
    temp.write_text(yaml.safe_dump(payload, sort_keys=False), encoding="utf-8")
    os.replace(temp, MKDOCS_NAV_YML)


def _sync_base_config_assets() -> None:
    """Mirror the base config's sibling assets next to the derived child config.

    OPERATIONAL INTENT — this is a correctness fix, not a convenience copy.

    MkDocs resolves *relative* config paths (``theme.custom_dir``, ``hooks``,
    and any future relative reference) against the directory of the config file
    it was invoked with — NOT the directory of the config that declared them.
    We build from the derived child config ``MKDOCS_NAV_YML`` in
    ``MKDOCS_CONFIG_DIR``, while the hand-maintained parent lives at
    ``MKDOCS_YML`` and is pulled in via ``INHERIT``. Whenever those two
    directories differ — which is the shipped compose layout,
    MKDOCS_BASE_CONFIG=/app/mkdocs/mkdocs.yml vs MKDOCS_CONFIG_DIR=/data/mkdocs
    — every relative path in the parent resolves into the child's directory and
    the build fails, e.g.

        Config value 'theme': The path set in custom_dir
        ('/data/mkdocs/overrides') does not exist.

    Mirroring the parent's siblings makes those relative paths resolve without
    parsing the parent YAML, which cannot be ``yaml.safe_load``ed: it carries
    an unsafe ``!!python/name:`` tag for the pymdownx mermaid custom fence.

    No-op when both configs already share a directory.
    """
    base_dir = MKDOCS_YML.parent
    if not base_dir.is_dir() or base_dir.resolve() == MKDOCS_CONFIG_DIR.resolve():
        return
    MKDOCS_CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    # Never copy the parent config itself, and never clobber the generated child.
    skip = {MKDOCS_YML.name, MKDOCS_NAV_YML.name}
    for source in base_dir.iterdir():
        if source.name in skip:
            continue
        destination = MKDOCS_CONFIG_DIR / source.name
        if source.is_dir():
            shutil.copytree(source, destination, dirs_exist_ok=True)
        else:
            shutil.copy2(source, destination)


def _build_site(redirect_sources: list[str] | None = None) -> int:
    started = time.monotonic()
    if STAGING_SITE_DIR.exists():
        shutil.rmtree(STAGING_SITE_DIR)
    _sync_base_config_assets()
    build = subprocess.run(
        ["mkdocs", "build", "--config-file", str(MKDOCS_NAV_YML), "--clean", "--site-dir", str(STAGING_SITE_DIR)],
        capture_output=True,
        text=True,
    )
    if build.returncode:
        raise RuntimeError(f"mkdocs build failed: {build.stderr[-2000:]}")
    # Verify compatibility routes in STAGING, before promotion. A recorded
    # redirect that produced no artifact must fail the deployment — otherwise the
    # release certifies as CURRENT while old URLs 404, which is precisely the
    # silent failure of docplane#65. Checking staging (not SITE_DIR) means a bad
    # release is never promoted in the first place.
    missing = [
        source for source in (redirect_sources or [])
        if not (STAGING_SITE_DIR / rendered_html_path(source)).is_file()
    ]
    if missing:
        raise RuntimeError(
            "redirect routes missing from the generated release: " + ", ".join(sorted(missing)[:20])
        )
    SITE_DIR.mkdir(parents=True, exist_ok=True)
    sync = subprocess.run(
        # SITE_INIT_SENTINEL is excluded from --delete on purpose. The compose
        # site-init service writes it to keep the docs-site volume non-empty,
        # which is what stops Docker repopulating the volume from the nginx
        # image and resetting its ownership to root. Deleting it here would
        # re-arm that failure for the next fresh container creation.
        [
            "rsync", "-a", "--checksum", "--delete",
            f"--exclude={SITE_INIT_SENTINEL}",
            f"{STAGING_SITE_DIR}/", f"{SITE_DIR}/",
        ],
        capture_output=True,
        text=True,
    )
    if sync.returncode:
        raise RuntimeError(f"site promotion failed: {sync.stderr[-2000:]}")
    return int((time.monotonic() - started) * 1000)


def run(
    pages: list[dict],
    dry_run: bool = False,
    section_order: dict[str, int] | None = None,
    redirects: dict[str, str] | None = None,
) -> dict:
    release_id = str(uuid4())
    for page in pages:
        if not str(page["path"]).endswith(".md"):
            raise RuntimeError(f"invalid page path: {page['path']}")
        if not str(page["content"]).strip():
            raise RuntimeError(f"empty page: {page['path']}")
    # Validated before the nav is built so unsound redirect state fails a dry run
    # too, rather than first surfacing at promotion time.
    compatibility = validate_redirects(dict(redirects or {}), pages)
    # One URL, one output. Checked after redirect validation so the more specific
    # redirect errors surface first, and before the nav so a dry run fails too.
    validate_routes(pages, compatibility)
    nav = build_nav(pages, section_order=section_order)
    if dry_run:
        return {
            "release_id": release_id,
            "dry_run": True,
            "pages": len(pages),
            "redirects": len(compatibility),
            "nav": nav,
        }

    stage = Path(tempfile.mkdtemp(prefix="docplane-corpus-"))
    try:
        managed: list[str] = []
        for page in pages:
            relative = Path(str(page["path"]))
            destination = stage / relative
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_text(_augment_content(page), encoding="utf-8")
            managed.append(relative.as_posix())
        DOCS_CONTENT_DIR.mkdir(parents=True, exist_ok=True)
        previous = set()
        try:
            previous = set(json.loads(MANIFEST_PATH.read_text()).get("managed_files", []))
        except (FileNotFoundError, json.JSONDecodeError):
            pass
        for path in previous - set(managed):
            target = DOCS_CONTENT_DIR / path
            if target.exists():
                target.unlink()
        for path in managed:
            source = stage / path
            target = DOCS_CONTENT_DIR / path
            target.parent.mkdir(parents=True, exist_ok=True)
            temp = target.with_suffix(target.suffix + ".tmp")
            shutil.copy2(source, temp)
            os.replace(temp, target)
        MANIFEST_PATH.write_text(
            json.dumps(
                {
                    "managed_files": sorted(managed),
                    "redirects": compatibility,
                    "release_id": release_id,
                    "published_at": datetime.now(timezone.utc).isoformat(),
                },
                indent=2,
            ),
            encoding="utf-8",
        )
        _write_nav(nav, compatibility)
        build_time_ms = _build_site(list(compatibility))
    finally:
        shutil.rmtree(stage, ignore_errors=True)
    return {
        "release_id": release_id,
        "dry_run": False,
        "pages": len(pages),
        "redirects": len(compatibility),
        "build_time_ms": build_time_ms,
    }
