"""Render the authoritative PostgreSQL corpus into an atomic MkDocs release."""
from __future__ import annotations

import json
import logging
import os
import re
import shutil
import subprocess
import tempfile
import time
from datetime import datetime, timezone
from pathlib import Path
from uuid import uuid4

import yaml

log = logging.getLogger(__name__)

DOCS_CONTENT_DIR = Path(os.environ.get("DOCS_CONTENT_DIR", "/docs-content"))
MKDOCS_CONFIG_DIR = Path(os.environ.get("MKDOCS_CONFIG_DIR", "/mkdocs-config"))
MKDOCS_YML = Path(os.environ.get("MKDOCS_BASE_CONFIG", str(MKDOCS_CONFIG_DIR / "mkdocs.yml")))
MKDOCS_NAV_YML = MKDOCS_CONFIG_DIR / "mkdocs.nav.yml"
SITE_DIR = Path(os.environ.get("DOCS_SITE_DIR", str(MKDOCS_CONFIG_DIR / "site")))
STAGING_SITE_DIR = Path(os.environ.get("DOCS_STAGING_SITE_DIR", "/tmp/docplane-site-build"))
MANIFEST_PATH = DOCS_CONTENT_DIR / ".docplane-manifest.json"
GENERATOR_STAMP = "<!-- Generated by DocPlane; edit through the API -->"
_NAV_PREFIX_RE = re.compile(r"^\d+\s+")


class NavConflict(RuntimeError):
    def __init__(self, kind: str, segment: str, message: str):
        self.kind = kind
        self.segment = segment
        self.message = message
        super().__init__(message)


def _augment_content(page: dict) -> str:
    content = str(page["content"])
    lines = [line for line in content.splitlines() if line.strip() != GENERATOR_STAMP]
    content = "\n".join(lines).rstrip() + "\n"
    updated_at = page.get("updated_at")
    version = page.get("version")
    if updated_at:
        if isinstance(updated_at, datetime):
            rendered = updated_at.astimezone(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        else:
            rendered = str(updated_at).replace("T", " ")[:16] + " UTC"
        marker = f"*Last updated: {rendered}{f' · v{version}' if version else ''}*"
        body = content.splitlines()
        body = [line for line in body if not re.match(r"^\*[Ll]ast updated:.*\*$", line.strip())]
        inserted = False
        output: list[str] = []
        for line in body:
            output.append(line)
            if not inserted and line.startswith("# "):
                output.extend(["", marker, ""])
                inserted = True
        if not inserted:
            output = [marker, ""] + output
        content = "\n".join(output).rstrip() + "\n"
    return f"{GENERATOR_STAMP}\n{content}"


def _normalize_segment(value: str) -> str:
    return _NAV_PREFIX_RE.sub("", value).strip().casefold()


def _insert(tree: dict, parts: list[str], path: str) -> None:
    node = tree
    for index, part in enumerate(parts):
        normalized = _normalize_segment(part)
        matching = next((key for key in node if _normalize_segment(key) == normalized), None)
        if matching is not None and matching != part:
            raise NavConflict(
                "case-collision",
                part,
                f"Navigation siblings {matching!r} and {part!r} normalize to the same name.",
            )
        key = matching or part
        leaf = index == len(parts) - 1
        existing = node.get(key)
        if leaf:
            if isinstance(existing, dict):
                raise NavConflict("leaf-vs-section", part, f"{part!r} is already a section.")
            if existing and existing != path:
                raise NavConflict("duplicate-leaf", part, f"{part!r} maps to multiple pages.")
            node[key] = path
        else:
            if isinstance(existing, str):
                raise NavConflict("leaf-vs-section", part, f"{part!r} is already a page.")
            node = node.setdefault(key, {})


def _serialize(tree: dict, *, top_level: bool, section_order: dict[str, int] | None) -> list:
    keys = list(tree)
    if top_level:
        order = section_order or {}
        keys.sort(key=lambda key: (order.get(key, 10_000), _normalize_segment(key)))
    else:
        keys.sort(key=_normalize_segment)
    result: list = []
    for key in keys:
        value = tree[key]
        result.append({key: _serialize(value, top_level=False, section_order=section_order) if isinstance(value, dict) else value})
    return result


def build_nav(pages: list[dict], *, strict: bool = True, section_order: dict[str, int] | None = None):
    tree: dict = {}
    conflicts: list[dict] = []
    home: str | None = None
    for page in pages:
        path = str(page["path"])
        nav_path = str(page["nav_path"])
        if nav_path == "Home":
            if home and home != path:
                conflict = NavConflict("duplicate-home", "Home", "Exactly one active page may be Home.")
                if strict:
                    raise conflict
                conflicts.append({"kind": conflict.kind, "segment": conflict.segment, "detail": conflict.message, "paths": [home, path]})
            home = path
            continue
        parts = [part.strip() for part in nav_path.split("/") if part.strip()]
        if len(parts) < 2:
            conflict = NavConflict("invalid", nav_path, "nav_path must contain a section and page label")
            if strict:
                raise conflict
            conflicts.append({"kind": conflict.kind, "segment": conflict.segment, "detail": conflict.message, "paths": [path]})
            continue
        try:
            _insert(tree, parts, path)
        except NavConflict as exc:
            if strict:
                raise
            conflicts.append({"kind": exc.kind, "segment": exc.segment, "detail": exc.message, "paths": [path]})
    nav = ([{"Home": home}] if home else []) + _serialize(tree, top_level=True, section_order=section_order)
    return nav if strict else (nav, conflicts)


def distinct_section_paths(pages: list[dict]) -> list[str]:
    sections: set[str] = set()
    for page in pages:
        nav_path = str(page["nav_path"])
        if nav_path == "Home":
            continue
        parts = nav_path.split("/")
        for index in range(1, len(parts)):
            sections.add("/".join(parts[:index]))
    return sorted(sections)


def _write_nav(nav: list) -> None:
    payload = {"INHERIT": str(MKDOCS_YML), "nav": nav}
    MKDOCS_NAV_YML.parent.mkdir(parents=True, exist_ok=True)
    temp = MKDOCS_NAV_YML.with_suffix(".tmp")
    temp.write_text(yaml.safe_dump(payload, sort_keys=False), encoding="utf-8")
    os.replace(temp, MKDOCS_NAV_YML)


def _build_site() -> int:
    started = time.monotonic()
    if STAGING_SITE_DIR.exists():
        shutil.rmtree(STAGING_SITE_DIR)
    build = subprocess.run(
        ["mkdocs", "build", "--config-file", str(MKDOCS_NAV_YML), "--clean", "--site-dir", str(STAGING_SITE_DIR)],
        capture_output=True,
        text=True,
    )
    if build.returncode:
        raise RuntimeError(f"mkdocs build failed: {build.stderr[-2000:]}")
    SITE_DIR.mkdir(parents=True, exist_ok=True)
    sync = subprocess.run(
        ["rsync", "-a", "--checksum", "--delete", f"{STAGING_SITE_DIR}/", f"{SITE_DIR}/"],
        capture_output=True,
        text=True,
    )
    if sync.returncode:
        raise RuntimeError(f"site promotion failed: {sync.stderr[-2000:]}")
    return int((time.monotonic() - started) * 1000)


def run(pages: list[dict], dry_run: bool = False, section_order: dict[str, int] | None = None) -> dict:
    release_id = str(uuid4())
    for page in pages:
        if not str(page["path"]).endswith(".md"):
            raise RuntimeError(f"invalid page path: {page['path']}")
        if not str(page["content"]).strip():
            raise RuntimeError(f"empty page: {page['path']}")
    nav = build_nav(pages, section_order=section_order)
    if dry_run:
        return {"release_id": release_id, "dry_run": True, "pages": len(pages), "nav": nav}

    stage = Path(tempfile.mkdtemp(prefix="docplane-corpus-"))
    try:
        managed: list[str] = []
        for page in pages:
            relative = Path(str(page["path"]))
            destination = stage / relative
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_text(_augment_content(page), encoding="utf-8")
            managed.append(relative.as_posix())
        DOCS_CONTENT_DIR.mkdir(parents=True, exist_ok=True)
        previous = set()
        try:
            previous = set(json.loads(MANIFEST_PATH.read_text()).get("managed_files", []))
        except (FileNotFoundError, json.JSONDecodeError):
            pass
        for path in previous - set(managed):
            target = DOCS_CONTENT_DIR / path
            if target.exists():
                target.unlink()
        for path in managed:
            source = stage / path
            target = DOCS_CONTENT_DIR / path
            target.parent.mkdir(parents=True, exist_ok=True)
            temp = target.with_suffix(target.suffix + ".tmp")
            shutil.copy2(source, temp)
            os.replace(temp, target)
        MANIFEST_PATH.write_text(
            json.dumps({"managed_files": sorted(managed), "release_id": release_id, "published_at": datetime.now(timezone.utc).isoformat()}, indent=2),
            encoding="utf-8",
        )
        _write_nav(nav)
        build_time_ms = _build_site()
    finally:
        shutil.rmtree(stage, ignore_errors=True)
    return {
        "release_id": release_id,
        "dry_run": False,
        "pages": len(pages),
        "build_time_ms": build_time_ms,
    }
