#!/usr/bin/env bash
# Seed a fresh install with a Home page + starter pages, then wait for the
# first site build. Idempotent — re-running overwrites the same seed pages
# (If-Match: * — explicit last-writer-wins).
set -euo pipefail

HERE="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck disable=SC1091
set -a; source "$HERE/.env"; set +a

API="${DOCS_API_LOCAL_URL:-http://localhost:8010}"
SITE="${DOCS_SITE_LOCAL_URL:-http://localhost:8080}"

command -v jq >/dev/null || { echo "jq is required" >&2; exit 1; }

put_page() {
    local path="$1" title="$2" nav="$3" content="$4"
    echo "PUT $path"
    jq -n --arg t "$title" --arg n "$nav" --arg c "$content" \
        '{title:$t, nav_path:$n, content:$c, updated_by:"seed-script"}' \
    | curl -sf -X PUT "$API/api/docs/pages/$path" \
        -H "X-API-Key: $DOCS_API_KEY" \
        -H "If-Match: *" \
        -H "Content-Type: application/json" \
        -d @- > /dev/null
}

put_page "index.md" "Home" "Home" \
"# Welcome

This site is generated by the self-hosted docs stack: every page lives in
PostgreSQL and is published through the docs API.

- Write pages with \`PUT /api/docs/pages/{path}\` — see the README.
- Connect an AI agent through the MCP server and use \`write_doc\`.
- This page is \`index.md\` with \`nav_path\` \`Home\` — replace it with your own.
"

put_page "guides/writing-pages.md" "Writing Pages" "Guides/Writing Pages" \
"# Writing Pages

Pages are Markdown with a required leading H1. \`path\` is the URL identity;
\`nav_path\` (like \`Guides/Writing Pages\`) is the sidebar location — they are
decoupled on purpose.

Updates need an \`If-Match\` header with the page's current revision (from a
GET), or \`If-Match: *\` to explicitly take last-writer-wins.

Every write triggers an automatic, coalesced rebuild — no manual deploy step.
"

# put_file <path> <title> <nav> <file> — like put_page but content from a file.
put_file() {
    local path="$1" title="$2" nav="$3" file="$4"
    echo "PUT $path (from $(basename "$file"))"
    python3 -c "
import json
print(json.dumps({
    'title': '$title',
    'nav_path': '$nav',
    'content': open('$file').read(),
    'updated_by': 'seed-script',
}))" | curl -sf -X PUT "$API/api/docs/pages/$path" \
        -H "X-API-Key: $DOCS_API_KEY" \
        -H "If-Match: *" \
        -H "Content-Type: application/json" \
        -d @- > /dev/null
}

# Agent-context fragments composed into each machine's CLAUDE.md by
# claude-md-sync (see claude-md/README.md). The templates carry FILL-IN
# markers — edit them via the API after seeding.
put_file "agent-context/doctrine.md" "Engineering Doctrine" "Agents/Doctrine" \
    "$HERE/claude-md/templates/doctrine.md"
put_file "agent-context/shared.md" "Shared Agent Context" "Agents/Shared Context" \
    "$HERE/claude-md/templates/shared-context.md"

# Publish the full API guide into the site itself, so the docs are self-hosting.
if [[ -f "$HERE/API_GUIDE.md" ]]; then
    echo "PUT guides/docs-api.md (from API_GUIDE.md)"
    python3 -c "
import json
print(json.dumps({
    'title': 'Docs API',
    'nav_path': 'Guides/Docs API',
    'content': open('$HERE/API_GUIDE.md').read(),
    'updated_by': 'seed-script',
}))" | curl -sf -X PUT "$API/api/docs/pages/guides/docs-api.md" \
        -H "X-API-Key: $DOCS_API_KEY" \
        -H "If-Match: *" \
        -H "Content-Type: application/json" \
        -d @- > /dev/null
fi

echo "Waiting for the site to build..."
for i in $(seq 1 30); do
    if curl -sf -o /dev/null "$SITE/"; then
        echo "Site is up: $SITE/"
        exit 0
    fi
    sleep 2
done
echo "Site not responding yet — check: docker compose logs docs-api docs-web" >&2
exit 1
